version: "3"

services:
  sd_tuning:
#    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
    container_name: sd_tuning
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
#    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data/dataset/:/data/dataset/
      - ./data/models/:/data/models/
