version: "3"

services:
  sd_tuning:
    image: nvidia/cuda:11.7-base
    container_name: sd_tuning
    build:
      context: ./
      dockerfile: Dockerfile
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data/dataset/:/app/data/dataset/
      - ./data/models/:/app/data/models/
